// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  GetUserByIdQueryRequest,
  GetUserByIdHeaderRequest,
  GetUserById200Response,
  GetMyInfoHeaderRequest,
  GetMyInfo200Response,
  GetUserByUsernameOrNicknameOrEmailQueryRequest,
  GetUserByUsernameOrNicknameOrEmailHeaderRequest,
  GetUserByUsernameOrNicknameOrEmail200Response,
  ModifyPasswordBodyRequest,
  ModifyPasswordHeaderRequest,
  ModifyPassword200Response,
  UserRegisterBodyRequest,
  UserRegister200Response,
  UserLoginBodyRequest,
  UserLogin200Response,
} from './namespaces';

export default class CDIServiceService<T> {
  private request: any = () => {
    throw new Error('CDIServiceService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 按用户 ID 查询用户资料 */
  GetUserByIdGET(
    req: GetUserByIdQueryRequest & GetUserByIdHeaderRequest,
    options?: T,
  ): Promise<GetUserById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/getUserById');
    const method = 'GET';
    const data = undefined;
    const params = { id: _req['id'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 从 Bearer 令牌查询当前用户资料 */
  GetMyInfoGET(
    req: GetMyInfoHeaderRequest,
    options?: T,
  ): Promise<GetMyInfo200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/getMyInfo');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按用户名、昵称或邮箱模糊查询用户 */
  GetUserByUsernameOrNicknameOrEmailGET(
    req: GetUserByUsernameOrNicknameOrEmailQueryRequest &
      GetUserByUsernameOrNicknameOrEmailHeaderRequest,
    options?: T,
  ): Promise<GetUserByUsernameOrNicknameOrEmail200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/getUserByUsernameOrNicknameOrEmail');
    const method = 'GET';
    const data = undefined;
    const params = {
      username_or_nickname_or_email: _req['username_or_nickname_or_email'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 校验旧密码后修改当前用户密码 */
  ModifyPasswordPOST(
    req: ModifyPasswordBodyRequest & ModifyPasswordHeaderRequest,
    options?: T,
  ): Promise<ModifyPassword200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/modifyPassword');
    const method = 'POST';
    const data = {
      old_password: _req['old_password'],
      new_password: _req['new_password'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 注册新用户 */
  UserRegisterPOST(
    req: UserRegisterBodyRequest,
    options?: T,
  ): Promise<UserRegister200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/register');
    const method = 'POST';
    const data = {
      username: _req['username'],
      password: _req['password'],
      nickname: _req['nickname'],
      email: _req['email'],
      role: _req['role'],
    };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 以用户名或邮箱和密码登录，签发JWT */
  UserLoginPOST(
    req: UserLoginBodyRequest,
    options?: T,
  ): Promise<UserLogin200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/login');
    const method = 'POST';
    const data = { username: _req['username'], password: _req['password'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
