// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface GetMyInfoHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetMyInfo200Response {
  /** 响应状态码 */
  status: number;
  /** 响应提示信息 */
  message: string;
  /** 当前用户信息 */
  user: GetMyInfo200ResponseUser;
}

export interface GetMyInfo200ResponseUser {
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 用户角色 */
  role: string;
  /** 用户等级 */
  level: number;
  /** 创建时间（ISO 8601） */
  created_at: string;
  /** 用户 ID */
  id: number;
  /** 是否配置本地密码 */
  has_password: boolean;
  /** 已绑定的第三方身份提供方 */
  auth_providers: string[];
}

export interface GetUserByUsernameOrNicknameOrEmailQueryRequest {
  /** 用户名、昵称或邮箱的关键字 */
  username_or_nickname_or_email: string;
}

export interface GetUserByUsernameOrNicknameOrEmailHeaderRequest {
  /** 认证令牌 */
  Authorization: string;
}

export interface GetUserByUsernameOrNicknameOrEmail200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
  /** 用户列表 */
  users: GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem[];
}

export interface GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem {
  /** 创建时间（ISO8601） */
  created_at: string;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 等级 */
  level: number;
  /** 用户 ID */
  id: number;
  /** 是否配置本地密码 */
  has_password: boolean;
  /** 已绑定的第三方身份提供方 */
  auth_providers: string[];
}

export interface ModifyPasswordHeaderRequest {
  /** 用户认证令牌 */
  Authorization: string;
}

export interface ModifyPasswordBodyRequest {
  /** 旧密码，无密码用户设置密码场景可为空 */
  old_password?: string | null;
  /** 新密码 */
  new_password: string;
}

export interface ModifyPassword200Response {
  /** 业务状态码 */
  status: number;
  /** 响应消息 */
  message: string;
}

export interface UserRegisterBodyRequest {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 昵称 */
  nickname: string;
  /** 邮箱 */
  email: string;
  /** 用户角色 */
  role: string;
}

export interface UserRegister200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
}

export interface UserLoginBodyRequest {
  /** 用户名或邮箱 */
  username: string;
  /** 密码 */
  password: string;
}

export interface UserLogin200Response {
  /** 业务状态码 */
  status: number;
  /** 提示信息 */
  message: string;
  /** JWT访问令牌，登录失败时不返回 */
  access_token?: string;
}

export interface GetUserByIdQueryRequest {
  /** 目标用户 ID */
  id: number;
}

export interface GetUserByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetUserById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 用户详细资料 */
  user: GetUserById200ResponseUser;
}

export interface GetUserById200ResponseUser {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 用户昵称 */
  nickname: string | null;
  /** 用户邮箱 */
  email: string | null;
  /** 用户角色，枚举 frontend、backend、fullstack、qa、devops、product_manager、designer、architect、proj_lead、guest */
  role: string;
  /** 用户等级，L0 至 L4 分别映射为 0 至 4 */
  level: number;
  /** 用户创建时间（ISO 8601） */
  created_at: string;
  /** 是否配置本地密码 */
  has_password: boolean;
  /** 已绑定的第三方身份提供方 */
  auth_providers: string[];
}

export interface UserGoogleLoginBodyRequest {
  /** Google Identity Services 返回的 ID Token */
  credential: string;
}

export interface UserGoogleLogin200Response {
  /** HTTP 状态码 */
  status: number;
  /** 提示信息 */
  message: string;
  /** 平台 JWT */
  access_token: string;
}

export interface UserGoogleLogin400Response {
  /** HTTP 状态码 */
  status: number;
  /** 错误信息：缺少 credential */
  message: string;
}

export interface UserGoogleLogin401Response {
  /** HTTP 状态码 */
  status: number;
  /** 错误信息：INVALID_GOOGLE_CREDENTIAL 或 UNVERIFIED_GOOGLE_ACCOUNT */
  message: string;
}

export interface UserGoogleLogin403Response {
  /** HTTP 状态码 */
  status: number;
  /** 错误信息：Google 域名不允许 */
  message: string;
}

export interface UserGoogleLogin409Response {
  /** HTTP 状态码 */
  status: number;
  /** 错误信息：邮箱已有本地账号，需要先密码登录后绑定 */
  message: string;
}

export interface UserGoogleLogin503Response {
  /** HTTP 状态码 */
  status: number;
  /** 错误信息：GOOGLE_AUTH_NOT_CONFIGURED 或 GOOGLE_AUTH_UNAVAILABLE */
  message: string;
}

export interface LinkGoogleHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface LinkGoogleBodyRequest {
  /** Google Identity Services 返回的 ID Token */
  credential: string;
}

export interface LinkGoogle200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
}
