// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface GetUserByIdQueryRequest {
  /** 用户 ID */
  id: number;
}

export interface GetUserByIdHeaderRequest {
  /** 授权令牌 */
  Authorization: string;
}

export interface GetUserById200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
  /** 用户信息，用户不存在时不返回 */
  user?: GetUserById200ResponseUser;
}

export interface GetUserById200ResponseUser {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 用户等级 */
  level: number;
  /** 创建时间（ISO8601） */
  created_at: string;
}

export interface GetMyInfoHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetMyInfo200Response {
  /** 响应状态码 */
  status: number;
  /** 响应提示信息 */
  message: string;
  /** 当前用户信息 */
  user: GetMyInfo200ResponseUser;
}

export interface GetMyInfo200ResponseUser {
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 用户角色 */
  role: string;
  /** 用户等级 */
  level: number;
  /** 创建时间（ISO 8601） */
  created_at: string;
  /** 用户 ID */
  id: number;
}

export interface GetUserByUsernameOrNicknameOrEmailQueryRequest {
  /** 用户名、昵称或邮箱的关键字 */
  username_or_nickname_or_email: string;
}

export interface GetUserByUsernameOrNicknameOrEmailHeaderRequest {
  /** 认证令牌 */
  Authorization: string;
}

export interface GetUserByUsernameOrNicknameOrEmail200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
  /** 用户列表 */
  users: GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem[];
}

export interface GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem {
  /** 用户 ID */
  id: number;
  /** 创建时间（ISO8601） */
  created_at: string;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 等级 */
  level: number;
}

export interface ModifyPasswordHeaderRequest {
  /** 用户认证令牌 */
  Authorization: string;
}

export interface ModifyPasswordBodyRequest {
  /** 旧密码 */
  old_password: string;
  /** 新密码 */
  new_password: string;
}

export interface ModifyPassword200Response {
  /** 业务状态码 */
  status: number;
  /** 响应消息 */
  message: string;
}

export interface UserRegisterBodyRequest {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 昵称 */
  nickname: string;
  /** 邮箱 */
  email: string;
  /** 用户角色 */
  role: string;
}

export interface UserRegister200Response {
  /** 响应状态码 */
  status: number;
  /** 响应消息 */
  message: string;
}

export interface UserLoginBodyRequest {
  /** 用户名或邮箱 */
  username: string;
  /** 密码 */
  password: string;
}

export interface UserLogin200Response {
  /** 业务状态码 */
  status: number;
  /** 提示信息 */
  message: string;
  /** JWT访问令牌，登录失败时不返回 */
  access_token?: string;
}
